# Generated by Django 3.2.7 on 2021-10-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_auto_20211008_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="phone_number",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="SickLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sickleave",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sick leave",
            },
        ),
    ]
