# Generated by Django 3.2.7 on 2021-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_annualleave"),
    ]

    operations = [
        migrations.AddField(
            model_name="sickleave",
            name="sick_reset",
            field=models.BooleanField(default=False),
        ),
    ]
