# Generated by Django 3.2.7 on 2021-10-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_sickleave_sick_reset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sickleave",
            name="sick_reset",
        ),
    ]
