# Generated by Django 3.2.9 on 2021-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_staff_tax_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="tax_number",
            field=models.IntegerField(),
        ),
    ]
