# Generated by Django 3.2.8 on 2021-11-25 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0007_remove_sickleave_sick_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='salarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basic_salary', models.IntegerField()),
                ('transport_allowance', models.IntegerField()),
                ('non_taxable_additional_allowances', models.IntegerField()),
                ('taxable_additional_allowances', models.IntegerField()),
                ('tax_deduction', models.IntegerField()),
                ('gross_salary', models.IntegerField()),
                ('net_salary', models.IntegerField()),
                ('json_salary', models.CharField(max_length=1000)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryslip', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Salary slip',
            },
        ),
    ]
