# Generated by Django 3.2.8 on 2021-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay_management", "0003_alter_salaryslip_tax_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryslip",
            name="tax_number",
            field=models.IntegerField(default=999),
        ),
    ]
